fix(utxo-lib): update assert imports for Node 22
Replace "*" imports with specific imports from
assert module. When upgrading the test runner
from ts-node to tsx, we need to fix imports to
be strictly ESM to avoid:
"TypeError: assert is not a function"

TICKET: WP-5599

TICKET: WP-5599